import { type LabContent } from '@/labs/lab-content.types';

export const CombinationalMultipliersContent: LabContent = {
  id: 'combinational-multipliers',
  title: 'Combinational Array Multiplier',
  labType: 'text',

  sections: [
    {
      id: 'theory',
      type: 'text',
      title: 'Theory',
      paragraphs: [
        'A combinational array multiplier computes the product of two n-bit unsigned binary numbers ' +
        'using a rectangular array of AND gates for partial product generation and a cascade of adder ' +
        'rows for partial product summation. The result is a 2n-bit product available combinationally ' +
        '(after a fixed propagation delay) with no clock cycles required.',

        'For two n-bit unsigned numbers $A = A_{n-1} \\ldots A_1 A_0$ and $B = B_{n-1} \\ldots B_1 B_0$, ' +
        'the partial product bit $PP_{ij} = A_i \\cdot B_j$ is generated by a single AND gate. ' +
        'There are $n^2$ AND gates in total. Each partial product $PP_j$ (= $A \\cdot B_j$) is an ' +
        'n-bit row that must be added to the previous accumulated sum, shifted left by j positions.',

        'The adder array structure: ' +
        'Row 0: PP0 is the first partial product (no addition needed). ' +
        'Row 1: PP0 + PP1 using a row of half adders (LSB) and full adders. ' +
        'Row 2: (Row 1 result) + PP2 using full adders. ' +
        'Row k: (Row k-1 result) + PPk. ' +
        'The final row produces the 2n-bit product. ' +
        'Total gate complexity: O(n²) AND gates and O(n²) adder gates.',

        'For a 4×4 array multiplier, the structure uses: 16 AND gates (partial products), ' +
        '4 half adders, and 8 full adders organized in 3 adder rows. ' +
        'The result is an 8-bit product with propagation delay O(n) gate levels.',

        'Signed multiplication (2\'s complement) requires modification. The Baugh-Wooley algorithm ' +
        'handles sign bits specially: for inputs A and B in 2\'s complement, the MSB has a negative ' +
        'weight ($-2^{n-1}$). The Baugh-Wooley array modifies the partial product generation for sign ' +
        'bits, inverting certain AND gate outputs and correcting with added constants, producing a ' +
        'correct signed product without a separate sign-extension step.',

        'Comparison: ' +
        'Unsigned array multiplier: $n^2$ AND + O(n²) FA, delay O(n). ' +
        'Signed Baugh-Wooley: same gate count with different connections, delay O(n). ' +
        'Both have O(n²) area and O(n) delay — slower than Wallace tree (O(log n)) but simpler to design ' +
        'and lay out in VLSI (regular, rectangular structure suitable for systematic place-and-route).',
      ],
    },

    {
      id: 'apparatus',
      type: 'apparatus',
      title: 'Apparatus Required',
      items: [
        { name: 'Pencil/Pen and Graph Paper', specification: 'For drawing the partial product array',    quantity: '1 set' },
        { name: 'Half/Full Adder Reference', specification: 'Truth tables and logic diagrams',            quantity: '1' },
        { name: 'Circuit Simulator (optional)', specification: 'Logisim / Digital for 4×4 array demo',   quantity: '1' },
        { name: 'Digital Design Textbook',  specification: 'Mano — Chapter on combinational multipliers', quantity: '1' },
      ],
    },

    {
      id: 'procedure',
      type: 'procedure',
      title: 'Procedure — 4×4 Unsigned Array Multiplier',
      steps: [
        {
          label: 'Draw the 4×4 partial product array.',
          body: 'For A = A3 A2 A1 A0 and B = B3 B2 B1 B0, draw a 4×4 grid of AND gates. ' +
            'Cell (i,j) computes PP_{ij} = A_i · B_j. ' +
            'Column c of the product P contains contributions from all cells where i+j = c. ' +
            'Label each AND gate output in the array.',
        },
        {
          label: 'Identify adder rows.',
          body: 'Row 1 sums PP_{0} and PP_{1} (shifted left 1). Use half adder for column 1, full adders for columns 2–4. ' +
            'Row 2 sums Row1 result with PP_{2} (shifted left 2). Full adders throughout. ' +
            'Row 3 sums Row2 result with PP_{3} (shifted left 3). Full adders throughout with carry-out chain.',
        },
        {
          label: 'Work through example: A=0b1010, B=0b0110.',
          body: 'A=10, B=6. Expected product: 60 = 0b0011 1100. ' +
            'Partial products: PP0 (B0=0): 0000. PP1 (B1=1): 1010<<1 = 10100. ' +
            'PP2 (B2=1): 1010<<2 = 101000. PP3 (B3=0): 0000. ' +
            'Sum: 0 + 10100 + 101000 + 0 = 111100 = 60 ✓.',
        },
        {
          label: 'Count gates and estimate delay.',
          body: 'AND gates: 4×4 = 16. Half adders: 4 (1 per adder row, LSB position). ' +
            'Full adders: approximately 8–12 depending on layout. ' +
            'Critical path: AND (1 level) → HA/FA chain (~6 levels) → final carry chain (~4 levels). ' +
            'Estimated total: ~11 gate levels for 4-bit multiplication.',
        },
      ],
    },

    {
      id: 'observations',
      type: 'observation',
      title: 'Observations',
      paragraphs: [
        'The 4×4 array multiplier has a regular, rectangular structure well-suited to VLSI layout.',
        'The O(n²) AND gate array generates all partial products simultaneously.',
        'Adder rows introduce O(n) delay due to the carry chain through the final adder row.',
      ],
      table: {
        headers: ['A (dec)', 'B (dec)', 'A × B (dec)', 'A × B (8-bit binary)'],
        rows: [
          [5, 3, 15, '0000 1111'],
          [10, 6, 60, '0011 1100'],
          [15, 15, 225, '1110 0001'],
          [7, 9, 63, '0011 1111'],
        ],
      },
    },

    {
      id: 'conclusion',
      type: 'conclusion',
      title: 'Conclusion',
      paragraphs: [
        'The combinational array multiplier provides a simple, regular structure for binary multiplication ' +
        'using n² AND gates for partial product generation and O(n²) adder gates for summation. The ' +
        'critical path delay is O(n) gate levels due to carry propagation through the adder rows.',

        'The regular array structure is advantageous for VLSI implementation as it allows systematic ' +
        'placement and routing. However, for high-speed applications, the O(n) delay is unacceptable, ' +
        'and Wallace tree or Dadda tree multipliers (O(log n) delay) are preferred.',

        'Signed multiplication using the Baugh-Wooley method extends the unsigned array approach to ' +
        '2\'s complement numbers with minimal additional logic, making it the signed equivalent of the ' +
        'unsigned array multiplier. Both are used as reference designs when understanding more complex ' +
        'optimized multiplier architectures.',
      ],
    },
  ],
};
