import Link from 'next/link';
import { Prose, DocEyebrow, Callout, DocNav, DocNavLink } from '@/sections/docs/doc-primitives';

export const metadata = {
  title: 'Docs — VLabs',
  description: 'Overview of the VLabs lab system and how to extend it.',
};

export default function DocsIndexPage() {
  return (
    <Prose>
      <DocEyebrow>Documentation</DocEyebrow>
      <h1>VLabs — Lab System Overview</h1>

      <p>
        VLabs is a Next.js application for interactive 3D electronics education.
        The lab system has two distinct layers that you can extend independently:
      </p>

      <ul>
        <li>
          <strong>Circuit definitions</strong> — plain TypeScript data files that declare
          which components go where and how to step through them. No renderer knowledge
          required. Designed to be generated by AI.
        </li>
        <li>
          <strong>Geometry builders</strong> — Three.js functions that turn a component
          instance into a 3D mesh. One function per component type.
        </li>
      </ul>

      <p>
        The renderer (<code>LabScene.tsx</code>) is fully data-driven through a
        <strong> component registry</strong> — a plain object that maps type strings to
        builder functions. Adding a new component type is a three-file edit with no
        changes to the renderer itself.
      </p>

      <hr />

      <h2>How the pieces fit together</h2>

      <pre>{`src/labs/
  types.ts              ← ComponentInstance union + Circuit type
  LabScene.tsx          ← Renderer + COMPONENT_REGISTRY
  coords.ts             ← hole() / railHole() coordinate helpers
  geometry/
    primitives.ts       ← solidBox, solidCyl, textLabel
    materials.ts        ← M.white(), M.dark(), M.gold() …
    breadboard.ts       ← buildBreadboard()
    ic.ts               ← buildDip14()
    components.ts       ← buildLed(), buildResistor(), buildWire()
    extra-components.ts ← buildCapacitor(), buildPotentiometer() …
    index.ts            ← barrel export
  circuits/
    index.ts            ← ALL_CIRCUITS registry
    half-adder/index.ts ← one file per circuit
    full-adder/index.ts
    …`}</pre>

      <h2>Quick orientation</h2>

      <table>
        <thead>
          <tr>
            <th>Task</th>
            <th>Files to edit</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Add a new <strong>circuit</strong> (new wiring of existing parts)</td>
            <td>
              <code>circuits/&lt;name&gt;/index.ts</code> (new file) +
              <code> circuits/index.ts</code>
            </td>
          </tr>
          <tr>
            <td>Add a new <strong>component type</strong> (new physical part)</td>
            <td>
              <code>types.ts</code> +
              <code> geometry/extra-components.ts</code> +
              <code> LabScene.tsx</code> (one registry entry)
            </td>
          </tr>
          <tr>
            <td>Generate a circuit with AI</td>
            <td>
              Paste <code>src/labs/COMPONENTS.md</code> into Claude, prompt, save output
            </td>
          </tr>
        </tbody>
      </table>

      <Callout $tone="tip">
        <strong>Using AI to generate circuits</strong>
        <p>
          The fastest workflow is: paste <code>src/labs/COMPONENTS.md</code> into
          Claude, say "Generate a full adder circuit", save the output to
          <code> src/labs/circuits/full-adder/index.ts</code>, then register it
          in <code>circuits/index.ts</code>. It renders immediately — no other
          changes needed.
        </p>
      </Callout>

      <h2>Pages in this guide</h2>

      <ul>
        <li><Link href="/docs/quickstart">Quickstart</Link> — add your first circuit in 5 minutes</li>
        <li><Link href="/docs/components">Component types</Link> — every renderable type and its props</li>
        <li><Link href="/docs/geometry">Writing geometry</Link> — how to build a new Three.js component</li>
        <li><Link href="/docs/registry">Registry &amp; renderer</Link> — how <code>COMPONENT_REGISTRY</code> works</li>
        <li><Link href="/docs/circuits">Circuit schema</Link> — the full <code>Circuit</code> type</li>
        <li><Link href="/docs/pins">Pin references</Link> — every <code>PinRef</code> variant explained</li>
        <li><Link href="/docs/steps">Steps &amp; highlighting</Link> — authoring step-by-step assembly</li>
        <li><Link href="/docs/columns">Column layout guide</Link> — placement rules for breadboard columns</li>
        <li><Link href="/docs/types">TypeScript types</Link> — full type reference</li>
        <li><Link href="/docs/constraints">Constraints &amp; rules</Link> — what the renderer expects</li>
      </ul>

      <DocNav>
        <span />
        <DocNavLink as={Link} href="/docs/quickstart" data-dir="next">
          Quickstart
        </DocNavLink>
      </DocNav>
    </Prose>
  );
}
